DOUBAN_API_KEY      = ""
DOUBAN_API_SECRET   = ""
DOUBAN_REDIRECT_URI = ""

DOUBAN_CODE          = ""
DOUBAN_TOKEN         = ""
DOUBAN_REFRESH_TOKEN = ""

DOUBAN_ROBOT_USERID   = 0
DOUBAN_ROBOT_USERNAME = ""
DOUBAN_ROBOT_EMAIL    = ""
DOUBAN_ROBOT_PWD      = ""

DOUBAN_ROBOT_COMMENT_TARGET_GROUP_TOPIC_ID = 0 
DOUBAN_ROBOT_COMMENT_TARGET_GROUP_TOPIC_FIRST_COMMENT_ID = 0 

